CREATE DATABASE QLDA;
GO

--DROP DATABASE QLDA

USE QLDA;
GO

CREATE TABLE DUAN(
   MaDA INT IDENTITY PRIMARY KEY,
   TenDA NVARCHAR(30),
   TienDo REAL,
   NgayKT DATE,
   NgayBD DATE,
   ChiPhi VARCHAR(30),
   GiaiDoan NVARCHAR(30),
   MaNV VARCHAR(10),
);

GO

CREATE TABLE CONGVIEC(
   MaCV INT IDENTITY PRIMARY KEY,
   TrangThai NVARCHAR(30) ,
   CVTienQuyet INT,
   TenCV NVARCHAR(30) ,
   TienDo REAL,
   TenNhom NVARCHAR(20),
   MaDA INT,
   MaSprint INT
);

GO

CREATE TABLE DIEMDANH(
   Ngay Date,
   MaNV VARCHAR(10),
   PRIMARY KEY(Ngay, MaNV),
   NoiDung NVARCHAR(20)
);

GO

CREATE TABLE UOCLUONG(
   MaNV VARCHAR(10),
   MaDA INT,
   MaSprint INT,
   PRIMARY KEY(MaNV, MaDA, MaSprint),
   SoNgayNghi INT,
   TimeSprint INT,
   TimeTasks INT,
);

GO

CREATE TABLE NHIEMVU
( 
  MaNhiemVu INT IDENTITY PRIMARY KEY,
  MaTienQuyet INT,
  TrangThai NVARCHAR(30),
  ThoiGianLamThucTe INT,
  TenNhiemVu NVARCHAR(30),
  ThoiGianUocTinh int,
  MaNV VARCHAR(10),
  MaCV INT,
)
GO

CREATE TABLE SPRINT (
	MaSprint INT IDENTITY PRIMARY KEY,
	NoiDung NVARCHAR(30),
	NgayBD DATE ,
	NgayKT DATE,
	MaDA INT
)
GO

CREATE TABLE TAINGUYEN (
	MaTN VARCHAR(10) PRIMARY KEY,
	TenTN NVARCHAR(20),
	LoaiTaiNguyen NVARCHAR(20),
)
GO

CREATE TABLE CAP (
	MaDA INT,
	MaTN VARCHAR(10),
	PRIMARY KEY(MaDA,MaTN)
)
GO

CREATE TABLE NHANVIEN (
	MaNV varchar(10) PRIMARY KEY,
	HovaTenDem nvarchar(25) ,
	Ten nvarchar(25) ,
	Email varchar(25),
	Levels varchar(10),
	DiaChi nvarchar(50),
	SDT varchar(20) ,
);
GO

CREATE TABLE TAIKHOAN (
	UserNames varchar(25) ,
	Passwords varchar(25) ,
	MaNV varchar(10)
);
GO

CREATE TABLE TEAMLEADER (
	TenNhom nvarchar(20) ,
	MaDA INT,
	MaNV varchar(10),
	PRIMARY KEY(TenNhom, MaDA)
);
GO

CREATE TABLE TEAM (
	MaNV varchar(10),
	TenNhom nvarchar(20),
	MaDA INT,
	CapPerDay INT,
	PRIMARY KEY(TenNhom, MaDA, MaNV)
);
GO

-- Adding constraint

ALTER TABLE TEAMLEADER ADD CONSTRAINT FK_TEAM_DUAN FOREIGN KEY(MaDA) REFERENCES DUAN(MaDA)  ON UPDATE CASCADE ;
ALTER TABLE TEAMLEADER ADD CONSTRAINT FK_TEAMLEADER_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE set null ON UPDATE CASCADE ; 
ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_TEAMLEADER FOREIGN KEY(TenNhom, MaDA) REFERENCES TEAMLEADER(TenNhom, MaDA)  ON UPDATE CASCADE ;
ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)   ; 
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)  ON DELETE SET NULL ON UPDATE CASCADE ;

alter table NHIEMVU add constraint PK_HIEMVU_NHANVIEN FOREIGN KEY (MaNV) references NHANVIEN(MaNV)  ON DELETE SET NULL ON UPDATE CASCADE ;
alter table NHIEMVU add constraint PK_NHIEMVU_CONGVIEC FOREIGN KEY (MaCV) references CONGVIEC(MaCV) ON DELETE SET NULL ON UPDATE CASCADE ;
alter table SPRINT add constraint PK_SPRINT_DUAN FOREIGN KEY (MaDA) references DUAN(MaDA)  ON DELETE SET NULL ON UPDATE CASCADE ;
alter table CAP add constraint PK_CAP_DUAN FOREIGN KEY (MaDA) references DUAN(MaDA) ON UPDATE CASCADE ;
alter table CAP add constraint PK_CAP_TAINGUYEN FOREIGN KEY (MaTN) references TAINGUYEN(MaTN)   ON UPDATE CASCADE ;

--RÀNG BUỘC VỚI BẢNG NHÂN VIÊN
ALTER TABLE DUAN ADD CONSTRAINT FK_DUAN_NHIEMVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)  ;
ALTER TABLE DIEMDANH ADD CONSTRAINT FK_DIEMDANH_NHIEMVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)  ON UPDATE CASCADE ;

--RÀNG BUỘC VỚI BẢNG TEAM
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_TEAMLEADER FOREIGN KEY (TenNhom, MaDA) REFERENCES TEAMLEADER(TenNhom,MaDA)  ON DELETE SET NULL ;

--RÀNG BUỘC VỚI SPRINT
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_SPRINT FOREIGN KEY (MaSprint) REFERENCES SPRINT(MaSprint) ON DELETE SET NULL ON UPDATE CASCADE ;

