//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDAEntities : DbContext
    {
        public QLDAEntities()
            : base("name=QLDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONGVIEC> CONGVIECs { get; set; }
        public virtual DbSet<DIEMDANH> DIEMDANHs { get; set; }
        public virtual DbSet<DUAN> DUANs { get; set; }
        public virtual DbSet<GIAIDOAN> GIAIDOANs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHIEMVU> NHIEMVUs { get; set; }
        public virtual DbSet<NHOM> NHOMs { get; set; }
        public virtual DbSet<TAINGUYEN> TAINGUYENs { get; set; }
        public virtual DbSet<TRUONGNHOM> TRUONGNHOMs { get; set; }
        public virtual DbSet<UOCLUONG> UOCLUONGs { get; set; }
    }
}
